# Generated by Django 3.1.7 on 2022-06-28 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_company_name', models.CharField(blank=True, max_length=240, null=True, verbose_name='Company Name')),
                ('sub_company_description', models.TextField(blank=True, null=True, verbose_name='Company Description')),
            ],
        ),
        migrations.CreateModel(
            name='LevelMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LevelPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_title', models.CharField(blank=True, max_length=40, null=True)),
                ('permission_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlantsDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plants_details', models.TextField(blank=True, null=True)),
                ('permissions', models.ManyToManyField(to='app1.LevelMapping')),
                ('sub_company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.companydetails')),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StorageLocationDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_location_details', models.TextField(blank=True, null=True)),
                ('permissions', models.ManyToManyField(to='app1.LevelMapping')),
                ('plants_details_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.plantsdetails')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrganisationDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_organisation_description', models.TextField(blank=True, null=True)),
                ('permissions', models.ManyToManyField(to='app1.LevelMapping')),
                ('sub_company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.companydetails')),
            ],
        ),
        migrations.CreateModel(
            name='ProductGroupDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_group_details', models.TextField(blank=True, null=True)),
                ('permissions', models.ManyToManyField(to='app1.LevelMapping')),
                ('sub_company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.companydetails')),
            ],
        ),
        migrations.CreateModel(
            name='MainCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=240, null=True)),
                ('company_description', models.TextField(blank=True, null=True)),
                ('permissions', models.ManyToManyField(to='app1.LevelMapping')),
            ],
        ),
        migrations.CreateModel(
            name='LocationsDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_details', models.TextField(blank=True, null=True)),
                ('permissions', models.ManyToManyField(to='app1.LevelMapping')),
                ('sub_company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.companydetails')),
            ],
        ),
        migrations.AddField(
            model_name='levelmapping',
            name='permissions',
            field=models.ManyToManyField(to='app1.LevelPermission'),
        ),
        migrations.AddField(
            model_name='levelmapping',
            name='user_id',
            field=models.ManyToManyField(to='app1.UserDetails'),
        ),
        migrations.CreateModel(
            name='DepartmentsDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departments_details', models.TextField(blank=True, null=True)),
                ('permissions', models.ManyToManyField(to='app1.LevelMapping')),
                ('plants_details_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.plantsdetails')),
            ],
        ),
        migrations.CreateModel(
            name='CostCentersDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_centers_details', models.TextField(blank=True, null=True)),
                ('permissions', models.ManyToManyField(to='app1.LevelMapping')),
                ('plants_details_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.plantsdetails')),
            ],
        ),
        migrations.AddField(
            model_name='companydetails',
            name='main_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.maincompany'),
        ),
        migrations.AddField(
            model_name='companydetails',
            name='permissions',
            field=models.ManyToManyField(to='app1.LevelMapping'),
        ),
    ]
