# Generated by Django 3.2.6 on 2022-06-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companydetails',
            old_name='permissions',
            new_name='level_mapping',
        ),
        migrations.RenameField(
            model_name='costcentersdetails',
            old_name='permissions',
            new_name='level_mapping',
        ),
        migrations.RenameField(
            model_name='departmentsdetails',
            old_name='permissions',
            new_name='level_mapping',
        ),
        migrations.RenameField(
            model_name='locationsdetails',
            old_name='permissions',
            new_name='level_mapping',
        ),
        migrations.RenameField(
            model_name='maincompany',
            old_name='permissions',
            new_name='level_mapping',
        ),
        migrations.RenameField(
            model_name='plantsdetails',
            old_name='permissions',
            new_name='level_mapping',
        ),
        migrations.RenameField(
            model_name='productgroupdetails',
            old_name='permissions',
            new_name='level_mapping',
        ),
        migrations.RenameField(
            model_name='purchaseorganisationdetails',
            old_name='permissions',
            new_name='level_mapping',
        ),
        migrations.RenameField(
            model_name='storagelocationdetails',
            old_name='permissions',
            new_name='level_mapping',
        ),
        migrations.RemoveField(
            model_name='levelmapping',
            name='level_name',
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='costcentersdetails',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='departmentsdetails',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='levelmapping',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='levelpermission',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='locationsdetails',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='maincompany',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='plantsdetails',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productgroupdetails',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='purchaseorganisationdetails',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='storagelocationdetails',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
