# Generated by Django 3.2.6 on 2022-06-28 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('app1', '0002_auto_20220628_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costcentersdetails',
            name='plants_details_data',
        ),
        migrations.RemoveField(
            model_name='departmentsdetails',
            name='plants_details_data',
        ),
        migrations.RemoveField(
            model_name='storagelocationdetails',
            name='plants_details_data',
        ),
        migrations.AddField(
            model_name='plantsdetails',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='plantsdetails',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
